### ISSUE TITLE
Building instructions missing

### ISSUE THREAD

**Issue by eMPee584** [nightscape/wavetuner#3]
uuhmm.. would like to pick this up but new to android dev'ing and can't even get the beast to build.. with "ant debug" all that scala stuff doesn't get included... is it impossible to build without eclipse?

**Comment by nightscape** [comment]
Hi Marcel,

unfortunately you can only build this from Eclipse right now.
I've added build instructions to the [README.md](https://github.com/nightscape/wavetuner/blob/master/README.md)
I just hacked them together from memory, could you give it a try and comment here if anything seems to be missing from the instructions?

Thanks!
  Martin

**Comment by eMPee584** [comment]
short follow-up: yes after coupl' of coupl' of hours messing around, I actually got it to build. Some adaptions of the project properties and a lot of go0gling were necessary though.. when I make further progress messing with it I'll update, probably with a pull req ;-)
eclipse is a naughty horned beast, btw^^
